sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (cargo install mdbook --vers 0.1.5 --force || true)
script:
  - bash ci/github_pages.sh
